# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddFriends.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addFriends(object):
    def setupUi(self, addFriends):
        addFriends.setObjectName("addFriends")
        addFriends.resize(681, 790)
        addFriends.setStyleSheet("QDialog    {\n"
"    background-color: rgb(13, 27, 67);\n"
"    border: 1px solid rgb(2, 130, 202);\n"
"}\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(45, 45, 68);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(80, 80, 122);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"/* HORIZONTAL SCROLLBAR - HOMEWORK */\n"
"QScrollBar:horizontal {\n"
"   \n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    \n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    \n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    \n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(addFriends)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(addFriends)
        self.frame_3.setMinimumSize(QtCore.QSize(64, 39))
        self.frame_3.setMaximumSize(QtCore.QSize(64, 39))
        self.frame_3.setStyleSheet("border-left:none;\n"
"border-bottom:none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setWhatsThis("")
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    height: 50px;\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(14, 163, 255, 70);\n"
"}")
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("feather/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.gridLayout.addWidget(self.frame_3, 0, 3, 1, 1)
        self.frame_4 = QtWidgets.QFrame(addFriends)
        self.frame_4.setMinimumSize(QtCore.QSize(64, 40))
        self.frame_4.setMaximumSize(QtCore.QSize(64, 40))
        self.frame_4.setStyleSheet("border-left:none;\n"
"border-top:none;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout.addWidget(self.frame_4, 2, 3, 1, 1)
        self.frame_2 = QtWidgets.QFrame(addFriends)
        self.frame_2.setMinimumSize(QtCore.QSize(64, 40))
        self.frame_2.setMaximumSize(QtCore.QSize(64, 40))
        self.frame_2.setStyleSheet("border-right:none;\n"
"border-top:none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout.addWidget(self.frame_2, 2, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(addFriends)
        self.frame_7.setStyleSheet("border: none;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_7)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 350))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget::pane{\n"
"    border-top: 1px solid rgb(2, 125, 202);\n"
"}\n"
"QTabBar::tab{\n"
"    background-color:rgba(0, 0, 0, 0);\n"
"    color: rgb(2, 125, 202);\n"
"    padding: 7px 15px 7px 15px;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background-color: rgb(8, 64, 98);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.Friends = QtWidgets.QWidget()
        self.Friends.setObjectName("Friends")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Friends)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_11 = QtWidgets.QFrame(self.Friends)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_11.setStyleSheet("background-color: rgb(13, 27, 67);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setLineWidth(0)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_10.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("height: 35px;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border: 2px solid rgb(8, 64, 98);\n"
"border-radius: 15px;\n"
"color: rgb(205, 235, 255);")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_10.addWidget(self.lineEdit_3)
        self.verticalLayout_6.addWidget(self.frame_11)
        self.frame_8 = QtWidgets.QFrame(self.Friends)
        self.frame_8.setStyleSheet("border: 1px solid rgb(2, 125, 202);\n"
"background-color: rgb(13, 27, 67);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_18 = QtWidgets.QFrame(self.frame_8)
        self.frame_18.setMaximumSize(QtCore.QSize(16777215, 0))
        self.frame_18.setStyleSheet("border:none;")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_23 = QtWidgets.QFrame(self.frame_18)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.gridLayout_6.addWidget(self.frame_23, 0, 0, 1, 1)
        self.frame_34 = QtWidgets.QFrame(self.frame_18)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.gridLayout_6.addWidget(self.frame_34, 2, 2, 1, 1)
        self.frame_39 = QtWidgets.QFrame(self.frame_18)
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_39)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_5 = QtWidgets.QLabel(self.frame_39)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(25)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(37, 234, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_25.addWidget(self.label_5)
        self.gridLayout_6.addWidget(self.frame_39, 1, 1, 1, 1)
        self.verticalLayout_19.addLayout(self.gridLayout_6)
        self.verticalLayout_12.addWidget(self.frame_18)
        self.listWidget_3 = QtWidgets.QListWidget(self.frame_8)
        self.listWidget_3.setStyleSheet("border:none;")
        self.listWidget_3.setObjectName("listWidget_3")
        self.verticalLayout_12.addWidget(self.listWidget_3)
        self.frame_19 = QtWidgets.QFrame(self.frame_8)
        self.frame_19.setMaximumSize(QtCore.QSize(16777215, 0))
        self.frame_19.setStyleSheet("border:none;")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_37 = QtWidgets.QFrame(self.frame_19)
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.gridLayout_7.addWidget(self.frame_37, 0, 0, 1, 1)
        self.frame_38 = QtWidgets.QFrame(self.frame_19)
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.gridLayout_7.addWidget(self.frame_38, 2, 2, 1, 1)
        self.frame_42 = QtWidgets.QFrame(self.frame_19)
        self.frame_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_42)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_6 = QtWidgets.QLabel(self.frame_42)
        self.label_6.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(25)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(2, 125, 202);")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../Images/loading.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_26.addWidget(self.label_6)
        self.gridLayout_7.addWidget(self.frame_42, 1, 1, 1, 1)
        self.verticalLayout_20.addLayout(self.gridLayout_7)
        self.verticalLayout_12.addWidget(self.frame_19)
        self.verticalLayout_6.addWidget(self.frame_8)
        self.tabWidget.addTab(self.Friends, "")
        self.AddFriends = QtWidgets.QWidget()
        self.AddFriends.setObjectName("AddFriends")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.AddFriends)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_9 = QtWidgets.QFrame(self.AddFriends)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_9.setStyleSheet("background-color: rgb(13, 27, 67);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setLineWidth(0)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_8.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("height: 35px;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border: 2px solid rgb(8, 64, 98);\n"
"border-radius: 15px;\n"
"color: rgb(205, 235, 255);\n"
"")
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_8.addWidget(self.lineEdit)
        self.verticalLayout_2.addWidget(self.frame_9)
        self.frame_5 = QtWidgets.QFrame(self.AddFriends)
        self.frame_5.setStyleSheet("border: 1px solid rgb(2, 125, 202);\n"
"background-color: rgb(13, 27, 67);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_12 = QtWidgets.QFrame(self.frame_5)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 0))
        self.frame_12.setStyleSheet("border:none;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_21 = QtWidgets.QFrame(self.frame_12)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.gridLayout_2.addWidget(self.frame_21, 0, 0, 1, 1)
        self.frame_24 = QtWidgets.QFrame(self.frame_12)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.gridLayout_2.addWidget(self.frame_24, 2, 2, 1, 1)
        self.frame_27 = QtWidgets.QFrame(self.frame_12)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label = QtWidgets.QLabel(self.frame_27)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(37, 234, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_22.addWidget(self.label)
        self.gridLayout_2.addWidget(self.frame_27, 1, 1, 1, 1)
        self.verticalLayout_13.addLayout(self.gridLayout_2)
        self.verticalLayout_7.addWidget(self.frame_12)
        self.listWidget = QtWidgets.QListWidget(self.frame_5)
        self.listWidget.setStyleSheet("QListWidget{\n"
"    border:none;\n"
"}\n"
"QListWidget::item{\n"
"    border-bottom: 1px solid rgb(7, 95, 154);\n"
"}")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_7.addWidget(self.listWidget)
        self.frame_13 = QtWidgets.QFrame(self.frame_5)
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 0))
        self.frame_13.setStyleSheet("border:none;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_29 = QtWidgets.QFrame(self.frame_13)
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.gridLayout_3.addWidget(self.frame_29, 0, 0, 1, 1)
        self.frame_26 = QtWidgets.QFrame(self.frame_13)
        self.frame_26.setMaximumSize(QtCore.QSize(200, 200))
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_2 = QtWidgets.QLabel(self.frame_26)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(25)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(2, 125, 202);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../Images/loading.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_15.addWidget(self.label_2)
        self.gridLayout_3.addWidget(self.frame_26, 1, 1, 1, 1)
        self.frame_30 = QtWidgets.QFrame(self.frame_13)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.gridLayout_3.addWidget(self.frame_30, 2, 2, 1, 1)
        self.verticalLayout_14.addLayout(self.gridLayout_3)
        self.verticalLayout_7.addWidget(self.frame_13)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.tabWidget.addTab(self.AddFriends, "")
        self.Pending = QtWidgets.QWidget()
        self.Pending.setObjectName("Pending")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Pending)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_10 = QtWidgets.QFrame(self.Pending)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_10.setStyleSheet("background-color: rgb(13, 27, 67);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setLineWidth(0)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_9.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("height: 35px;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border: 2px solid rgb(8, 64, 98);\n"
"border-radius: 15px;\n"
"color: rgb(205, 235, 255);")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_9.addWidget(self.lineEdit_2)
        self.verticalLayout_5.addWidget(self.frame_10)
        self.frame_6 = QtWidgets.QFrame(self.Pending)
        self.frame_6.setStyleSheet("border: 1px solid rgb(2, 125, 202);\n"
"background-color: rgb(13, 27, 67);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_15 = QtWidgets.QFrame(self.frame_6)
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 0))
        self.frame_15.setStyleSheet("border:none;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_31 = QtWidgets.QFrame(self.frame_15)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.gridLayout_4.addWidget(self.frame_31, 0, 0, 1, 1)
        self.frame_32 = QtWidgets.QFrame(self.frame_15)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.gridLayout_4.addWidget(self.frame_32, 2, 2, 1, 1)
        self.frame_35 = QtWidgets.QFrame(self.frame_15)
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_35)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_3 = QtWidgets.QLabel(self.frame_35)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(25)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(37, 234, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_23.addWidget(self.label_3)
        self.gridLayout_4.addWidget(self.frame_35, 1, 1, 1, 1)
        self.verticalLayout_16.addLayout(self.gridLayout_4)
        self.verticalLayout_11.addWidget(self.frame_15)
        self.listWidget_2 = QtWidgets.QListWidget(self.frame_6)
        self.listWidget_2.setStyleSheet("border:none;")
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_11.addWidget(self.listWidget_2)
        self.frame_16 = QtWidgets.QFrame(self.frame_6)
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 0))
        self.frame_16.setStyleSheet("border:none;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_22 = QtWidgets.QFrame(self.frame_16)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.gridLayout_5.addWidget(self.frame_22, 0, 0, 1, 1)
        self.frame_33 = QtWidgets.QFrame(self.frame_16)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.gridLayout_5.addWidget(self.frame_33, 2, 2, 1, 1)
        self.frame_36 = QtWidgets.QFrame(self.frame_16)
        self.frame_36.setMaximumSize(QtCore.QSize(200, 200))
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_36)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_4 = QtWidgets.QLabel(self.frame_36)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(25)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(2, 125, 202);")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../Images/loading.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_24.addWidget(self.label_4)
        self.gridLayout_5.addWidget(self.frame_36, 1, 1, 1, 1)
        self.verticalLayout_17.addLayout(self.gridLayout_5)
        self.verticalLayout_11.addWidget(self.frame_16)
        self.verticalLayout_5.addWidget(self.frame_6)
        self.tabWidget.addTab(self.Pending, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.gridLayout.addWidget(self.frame_7, 1, 1, 1, 1)
        self.frame = QtWidgets.QFrame(addFriends)
        self.frame.setMinimumSize(QtCore.QSize(564, 0))
        self.frame.setStyleSheet("border-right:none;\n"
"border-bottom:none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(addFriends)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(addFriends)

    def retranslateUi(self, addFriends):
        _translate = QtCore.QCoreApplication.translate
        addFriends.setWindowTitle(_translate("addFriends", "Dialog"))
        self.lineEdit_3.setPlaceholderText(_translate("addFriends", "Enter UserID"))
        self.label_5.setText(_translate("addFriends", "Not Found"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Friends), _translate("addFriends", "Friends"))
        self.lineEdit.setPlaceholderText(_translate("addFriends", "Enter UserID"))
        self.label.setText(_translate("addFriends", "Not Found"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AddFriends), _translate("addFriends", "Add Friends"))
        self.lineEdit_2.setPlaceholderText(_translate("addFriends", "Enter UserID "))
        self.label_3.setText(_translate("addFriends", "Not Found"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Pending), _translate("addFriends", "Pending"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addFriends = QtWidgets.QDialog()
    ui = Ui_addFriends()
    ui.setupUi(addFriends)
    addFriends.show()
    sys.exit(app.exec_())
