# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Capture.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Capture(object):
    def setupUi(self, Capture):
        Capture.setObjectName("Capture")
        Capture.resize(511, 251)
        Capture.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.pushButton = QtWidgets.QPushButton(Capture)
        self.pushButton.setGeometry(QtCore.QRect(70, 120, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color: rgb(99, 255, 250);\n"
"    border:1px solid rgb(99, 255, 250);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(99, 255, 250);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Capture)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 120, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    color: rgb(99, 255, 250);\n"
"    border:1px solid rgb(99, 255, 250);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(99, 255, 250);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Capture)
        self.pushButton_3.setGeometry(QtCore.QRect(440, 10, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    background-color:rgba(0,0,0,0);\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    color:rgb(255,255,255)\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(Capture)
        self.label.setGeometry(QtCore.QRect(0, 0, 511, 251))
        self.label.setStyleSheet("border:1px solid rgb(255, 0, 4);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Capture)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 491, 51))
        self.label_2.setStyleSheet("border-top:1px solid rgb(255, 0, 4);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label_2.raise_()
        self.pushButton_3.raise_()

        self.retranslateUi(Capture)
        QtCore.QMetaObject.connectSlotsByName(Capture)

    def retranslateUi(self, Capture):
        _translate = QtCore.QCoreApplication.translate
        Capture.setWindowTitle(_translate("Capture", "Dialog"))
        self.pushButton.setText(_translate("Capture", "Choose"))
        self.pushButton_2.setText(_translate("Capture", "Camera"))
        self.pushButton_3.setText(_translate("Capture", "X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Capture = QtWidgets.QDialog()
    ui = Ui_Capture()
    ui.setupUi(Capture)
    Capture.show()
    sys.exit(app.exec_())
