# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Home.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(1355, 914)
        Home.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(45, 45, 68);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(80, 80, 122);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"/* HORIZONTAL SCROLLBAR - HOMEWORK */\n"
"QScrollBar:horizontal {\n"
"   \n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    \n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    \n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    \n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(Home)
        self.centralwidget.setStyleSheet("background-color: rgb(13, 27, 67);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setStyleSheet("border-bottom:1px solid rgba(5, 107, 202, 150);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_26 = QtWidgets.QFrame(self.frame)
        self.frame_26.setStyleSheet("border-bottom:none;")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.frame_26)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(205, 235, 255);\n"
"padding-left: 10px;")
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.horizontalLayout_13.addWidget(self.frame_26)
        self.frame_27 = QtWidgets.QFrame(self.frame)
        self.frame_27.setMaximumSize(QtCore.QSize(170, 16777215))
        self.frame_27.setStyleSheet("QFrame{\n"
"    border-bottom:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(14, 163, 255, 100);\n"
"}")
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_27)
        self.pushButton_11.setStyleSheet("height: 50px;\n"
"border:none;")
        self.pushButton_11.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../../../../Test/Res/Templates/feather/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_14.addWidget(self.pushButton_11)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_27)
        self.pushButton_10.setStyleSheet("height: 50px;\n"
"border:none;")
        self.pushButton_10.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\../../../../Test/Res/Templates/feather/restore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon1)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_14.addWidget(self.pushButton_10)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_27)
        self.pushButton_9.setWhatsThis("")
        self.pushButton_9.setStyleSheet("height: 50px;\n"
"border:none;")
        self.pushButton_9.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\../../../../Test/Res/Templates/feather/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon2)
        self.pushButton_9.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_14.addWidget(self.pushButton_9)
        self.horizontalLayout_13.addWidget(self.frame_27)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMinimumSize(QtCore.QSize(340, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_4.setStyleSheet("border-right:1px solid rgba(5, 107, 202, 150);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_6.setStyleSheet("border-right: none;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_8.setStyleSheet("background-color: rgba(8, 64, 98, 100);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setLineWidth(0)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_2.setContentsMargins(5, 0, 0, 5)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_15 = QtWidgets.QFrame(self.frame_8)
        self.frame_15.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frame_15.setStyleSheet("background-color: none;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_7.setGeometry(QtCore.QRect(5, 10, 45, 38))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    background-color:rgba(0, 0, 0, 0);\n"
"    border-radius: 18px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 30);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_6 = QtWidgets.QLabel(self.frame_15)
        self.label_6.setGeometry(QtCore.QRect(5, 10, 45, 38))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(".\\../Images/249765516122.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_6.raise_()
        self.pushButton_7.raise_()
        self.horizontalLayout_2.addWidget(self.frame_15)
        self.frame_13 = QtWidgets.QFrame(self.frame_8)
        self.frame_13.setStyleSheet("background-color: none;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_2.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_8)
        self.frame_14.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_14.setStyleSheet("background-color: none;")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_17 = QtWidgets.QFrame(self.frame_14)
        self.frame_17.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frame_17.setStyleSheet("border:none;\n"
"height: 50px;")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_2.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 30);\n"
"    border-radius: 15px;\n"
"}")
        self.pushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\../../../../Test/Res/Templates/feather/plus1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_17.addWidget(self.pushButton_2)
        self.horizontalLayout_3.addWidget(self.frame_17)
        self.frame_16 = QtWidgets.QFrame(self.frame_14)
        self.frame_16.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frame_16.setStyleSheet("border:none;\n"
"height: 50px;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.frame_16)
        self.pushButton.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 30);\n"
"    border-radius: 15px;\n"
"}")
        self.pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\../../../../Test/Res/Templates/feather/menu1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(35, 35))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.horizontalLayout_3.addWidget(self.frame_16)
        self.horizontalLayout_2.addWidget(self.frame_14)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_6)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_9.setStyleSheet("")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setLineWidth(0)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_8.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("height: 35px;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border: 2px solid rgb(8, 64, 98);\n"
"border-radius: 15px;\n"
"color: rgb(205, 235, 255);")
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_8.addWidget(self.lineEdit)
        self.verticalLayout_5.addWidget(self.frame_9)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 400))
        self.frame_7.setStyleSheet("border-right: none;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listWidget = QtWidgets.QListWidget(self.frame_7)
        self.listWidget.setStyleSheet("QListWidget{\n"
"    border:none;\n"
"    border-top:1px solid rgba(5, 107, 202, 150);\n"
"}\n"
"QListWidget::item{\n"
"    height: 50px;\n"
"    border-bottom: 1px solid rgb(7, 95, 154);\n"
"}\n"
"QListWidget::item:selected{\n"
"    background-color: rgba(4, 140, 167, 100);\n"
"    border: none;\n"
"}\n"
"QListWidget::item:focus{\n"
"    border: none;\n"
"}")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_4.addWidget(self.listWidget)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setMinimumSize(QtCore.QSize(550, 0))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_11 = QtWidgets.QFrame(self.frame_5)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_31 = QtWidgets.QFrame(self.frame_11)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.gridLayout.addWidget(self.frame_31, 0, 0, 1, 1)
        self.frame_36 = QtWidgets.QFrame(self.frame_11)
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.gridLayout.addWidget(self.frame_36, 2, 2, 1, 1)
        self.frame_37 = QtWidgets.QFrame(self.frame_11)
        self.frame_37.setMinimumSize(QtCore.QSize(400, 300))
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_37)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_39 = QtWidgets.QFrame(self.frame_37)
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_39)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_3 = QtWidgets.QLabel(self.frame_39)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(30)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(2, 125, 202);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_20.addWidget(self.label_3)
        self.verticalLayout_19.addWidget(self.frame_39)
        self.frame_40 = QtWidgets.QFrame(self.frame_37)
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_40)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_4 = QtWidgets.QLabel(self.frame_40)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(2, 125, 202);")
        self.label_4.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_21.addWidget(self.label_4)
        self.verticalLayout_19.addWidget(self.frame_40)
        self.gridLayout.addWidget(self.frame_37, 1, 1, 1, 1)
        self.verticalLayout_22.addLayout(self.gridLayout)
        self.verticalLayout_6.addWidget(self.frame_11)
        self.frame_10 = QtWidgets.QFrame(self.frame_5)
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 0))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_19 = QtWidgets.QFrame(self.frame_10)
        self.frame_19.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_19.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_19.setStyleSheet("background-color: rgba(8, 64, 98, 100);\n"
"border-bottom:1px solid rgba(5, 107, 202, 150);")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_7.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_20 = QtWidgets.QFrame(self.frame_19)
        self.frame_20.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frame_20.setStyleSheet("background-color: none;")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 0, 60, 58))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 30);\n"
"    border-radius: 15px;\n"
"}")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_5 = QtWidgets.QLabel(self.frame_20)
        self.label_5.setGeometry(QtCore.QRect(5, 4, 50, 50))
        self.label_5.setStyleSheet("border:2px solid rgb(5, 107, 202);\n"
"border-radius: 24px;")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(".\\../Images/249765516122.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_5.raise_()
        self.pushButton_6.raise_()
        self.horizontalLayout_7.addWidget(self.frame_20)
        self.frame_29 = QtWidgets.QFrame(self.frame_19)
        self.frame_29.setStyleSheet("background-color: none;")
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_2 = QtWidgets.QLabel(self.frame_29)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(205, 235, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_15.addWidget(self.label_2)
        self.horizontalLayout_7.addWidget(self.frame_29)
        self.frame_30 = QtWidgets.QFrame(self.frame_19)
        self.frame_30.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frame_30.setStyleSheet("border:none;\n"
"height: 50px;\n"
"background-color: none;")
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_30)
        self.pushButton_3.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 30);\n"
"    border-radius: 15px;\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setIcon(icon4)
        self.pushButton_3.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.horizontalLayout_7.addWidget(self.frame_30)
        self.verticalLayout_18.addWidget(self.frame_19)
        self.frame_18 = QtWidgets.QFrame(self.frame_10)
        self.frame_18.setStyleSheet("")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_32 = QtWidgets.QFrame(self.frame_18)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_32)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_33 = QtWidgets.QFrame(self.frame_32)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.gridLayout_3.addWidget(self.frame_33, 0, 0, 1, 1)
        self.frame_34 = QtWidgets.QFrame(self.frame_32)
        self.frame_34.setMaximumSize(QtCore.QSize(200, 200))
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_34)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.frame_34)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(".\\../Images/loading.gif"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.gridLayout_3.addWidget(self.frame_34, 1, 1, 1, 1)
        self.frame_35 = QtWidgets.QFrame(self.frame_32)
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.gridLayout_3.addWidget(self.frame_35, 2, 2, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_3)
        self.verticalLayout_12.addWidget(self.frame_32)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_18)
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 0))
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setStyleSheet("QScrollArea{\n"
"border:none;\n"
"padding: 10px;\n"
"}\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 863, 16))
        font = QtGui.QFont()
        self.scrollAreaWidgetContents.setFont(font)
        self.scrollAreaWidgetContents.setStyleSheet("QLabel{\n"
"    color: rgb(205, 235, 255);\n"
"    height: 30px;\n"
"}")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_22 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(10)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_13.addWidget(self.frame_22, 0, QtCore.Qt.AlignTop)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_12.addWidget(self.scrollArea)
        self.verticalLayout_18.addWidget(self.frame_18)
        self.frame_12 = QtWidgets.QFrame(self.frame_10)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_12.setStyleSheet("background-color: rgba(8, 64, 98, 100);\n"
"border-top:1px solid rgba(5, 107, 202, 150);")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_8.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_8.setSpacing(7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_23 = QtWidgets.QFrame(self.frame_12)
        self.frame_23.setMinimumSize(QtCore.QSize(60, 0))
        self.frame_23.setStyleSheet("border:none;\n"
"height: 50px;\n"
"background-color: none;")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_23)
        self.pushButton_5.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 30);\n"
"    border-radius: 15px;\n"
"}")
        self.pushButton_5.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(".\\../../../../Test/Res/Templates/feather/attach.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon5)
        self.pushButton_5.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_9.addWidget(self.pushButton_5)
        self.horizontalLayout_8.addWidget(self.frame_23)
        self.frame_21 = QtWidgets.QFrame(self.frame_12)
        self.frame_21.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_21.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border:none;")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setLineWidth(0)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_21)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("height: 35px;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border: 2px solid rgb(8, 64, 98);\n"
"border-radius: 15px;\n"
"color: rgb(205, 235, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_11.addWidget(self.lineEdit_2)
        self.horizontalLayout_8.addWidget(self.frame_21)
        self.frame_28 = QtWidgets.QFrame(self.frame_12)
        self.frame_28.setMinimumSize(QtCore.QSize(60, 0))
        self.frame_28.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frame_28.setStyleSheet("border:none;\n"
"height: 50px;\n"
"background-color: none;")
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_28)
        self.pushButton_4.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 30);\n"
"    border-radius: 15px;\n"
"}")
        self.pushButton_4.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(".\\../../../../Test/Res/Templates/feather/send1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon6)
        self.pushButton_4.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_10.addWidget(self.pushButton_4)
        self.horizontalLayout_8.addWidget(self.frame_28)
        self.verticalLayout_18.addWidget(self.frame_12)
        self.verticalLayout_6.addWidget(self.frame_10)
        self.horizontalLayout.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setStyleSheet("border-top:1px solid rgba(5, 107, 202, 150);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_12.setContentsMargins(15, 0, 5, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_24 = QtWidgets.QFrame(self.frame_3)
        self.frame_24.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frame_24.setStyleSheet("border:none;\n"
"height: 50px;\n"
"background-color:rgba(0, 0, 0, 0);")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_24)
        self.pushButton_8.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 30);\n"
"    border-radius: 15px;\n"
"}")
        self.pushButton_8.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(".\\../../../../Test/Res/Templates/feather/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon7)
        self.pushButton_8.setIconSize(QtCore.QSize(35, 32))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_11.addWidget(self.pushButton_8)
        self.horizontalLayout_12.addWidget(self.frame_24)
        self.frame_25 = QtWidgets.QFrame(self.frame_3)
        self.frame_25.setStyleSheet("border-top:none;")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_12.addWidget(self.frame_25)
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        Home.setCentralWidget(self.centralwidget)

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "MainWindow"))
        self.label.setText(_translate("Home", "Message Parsel"))
        self.lineEdit.setPlaceholderText(_translate("Home", "Search Person"))
        self.label_3.setText(_translate("Home", "Fly Messenger"))
        self.label_4.setText(_translate("Home", "Send and Receive messages easily"))
        self.label_2.setWhatsThis(_translate("Home", "<html><head/><body><p>bfgbgbfgbfgbfgb</p><p><span style=\" font-size:8pt;\">bfgbgbgf</span></p></body></html>"))
        self.label_2.setText(_translate("Home", "Username"))
        self.lineEdit_2.setPlaceholderText(_translate("Home", "Enter the message here..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Home = QtWidgets.QMainWindow()
    ui = Ui_Home()
    ui.setupUi(Home)
    Home.show()
    sys.exit(app.exec_())
