# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Loading(object):
    def setupUi(self, Loading):
        Loading.setObjectName("Loading")
        Loading.resize(400, 300)
        self.widget = QtWidgets.QWidget(Loading)
        self.widget.setGeometry(QtCore.QRect(40, 50, 311, 181))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(60, 60, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgba(8, 64, 98, 150);\n"
"color: rgb(21, 205, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Loading)
        QtCore.QMetaObject.connectSlotsByName(Loading)

    def retranslateUi(self, Loading):
        _translate = QtCore.QCoreApplication.translate
        Loading.setWindowTitle(_translate("Loading", "Dialog"))
        self.label.setText(_translate("Loading", "Loading..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Loading = QtWidgets.QDialog()
    ui = Ui_Loading()
    ui.setupUi(Loading)
    Loading.show()
    sys.exit(app.exec_())
